```yaml
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: $CI_REGISTRY_IMAGE

stages:
  - build

build_and_push:
  stage: build
  script:
    # Login ke GitLab Container Registry
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

    # Build image
    - docker build -t $IMAGE_NAME:latest .

    # Push image ke GitLab Registry
    - docker push $IMAGE_NAME:latest
```
